# Generated by Django 4.0.1 on 2023-04-28 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_person_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Student',
        ),
    ]
