# Generated by Django 4.0.1 on 2023-04-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_person_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('f_age', models.DateField(blank=True, null=True)),
                ('f_careers', models.CharField(max_length=100)),
                ('f_address', models.CharField(max_length=200)),
                ('f_contact', models.CharField(max_length=100)),
                ('f_image', models.ImageField(blank=True, null=True, upload_to='father-image')),
            ],
        ),
    ]
