# Generated by Django 4.0.1 on 2023-04-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_father'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Father',
        ),
        migrations.AddField(
            model_name='student',
            name='f_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='f_age',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='f_careers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='f_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='f_image',
            field=models.ImageField(blank=True, null=True, upload_to='father-image'),
        ),
        migrations.AddField(
            model_name='student',
            name='f_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='m_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='m_age',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='m_careers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='m_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='m_image',
            field=models.ImageField(blank=True, null=True, upload_to='mother-image'),
        ),
        migrations.AddField(
            model_name='student',
            name='m_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
