# Generated by Django 4.0.1 on 2023-03-31 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_religion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serviced_Place',
            new_name='Rank',
        ),
    ]
