# Generated by Django 4.0.6 on 2023-03-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_serviced_place_rank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Current_Department',
            new_name='Department',
        ),
    ]
