# Generated by Django 4.1.5 on 2023-04-04 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_personal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
