# Generated by Django 4.1.5 on 2023-04-04 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ser_number', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='personal-image')),
                ('gender', models.CharField(max_length=20)),
                ('birthday', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
                ('married', models.CharField(max_length=100)),
                ('health', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('batch_no', models.CharField(max_length=50)),
                ('serviced', models.TextField(max_length=200)),
                ('crime', models.TextField(blank=True, max_length=250, null=True)),
                ('blood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.blood')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.nation')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rank')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.religion')),
                ('trained_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainingground')),
                ('trained_type', models.ManyToManyField(to='myapp.trainingtype')),
            ],
        ),
    ]
