# Generated by Django 4.1.5 on 2023-04-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='birthday',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='join_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
