# Generated by Django 4.1.5 on 2023-04-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_personal_birthday_alter_personal_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='birthday',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
