# Generated by Django 4.1.5 on 2023-04-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_crime_commander_crime_crime_type_crime_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ManyToManyField(to='myapp.department')),
            ],
        ),
    ]
