# Generated by Django 4.1.5 on 2023-04-20 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_serviced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviced',
            old_name='name',
            new_name='serviced',
        ),
    ]
