# Generated by Django 4.0.1 on 2023-04-21 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_name_serviced_serviced'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment'),
        ),
        migrations.DeleteModel(
            name='Serviced',
        ),
    ]
