# Generated by Django 4.0.1 on 2023-04-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_servicedplace_long_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedplace',
            name='serviced',
        ),
        migrations.AddField(
            model_name='servicedplace',
            name='serviced',
            field=models.ManyToManyField(to='myapp.Department'),
        ),
    ]
