# Generated by Django 4.0.6 on 2023-05-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_photo_description_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
