# Generated by Django 4.0.6 on 2023-05-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_photo_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='description',
            new_name='title',
        ),
    ]
